# Generated by Django 5.2 on 2025-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='marriage_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
