# Generated by Django 5.2 on 2025-04-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='marriage_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
